name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  release:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    # NOTE: fetch all histories of the repositories to create changelog.
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build packages
      run: |
        python -m build

    - name: Release package
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
